### ISSUE TITLE
deactivate Contentful

### ISSUE THREAD

**Issue by astridx** [escapemanuele/gatsby-contentful-blog-portfolio#5]
Hello,
I am new with Gatsby and I like this theme. 
Is it possible to deactivate Contentful or do I Need to use it if I use this theme?

**Comment by escapemanuele** [comment]
Hi astridx! Sorry for the late response.
Well, if you don't want to use the blog and portfolio pages, you could try deleting them and also deleting the gatsby-node content :)

**Comment by astridx** [comment]
Thanks for answering. I managed it meanwhile :)
